## Dear Diary: Ritual Communication and the Mediated Self

Since this week's reading assignment is about media practices and their social function, let me start by asking you to describe your own practice in relation to a very specific question: do you keep a diary, whether daily, weekly, or occasional? If so, which format do you use: analog, digital, or perhaps both? Do you keep your diary private, or do you share it with family, friends, or publicly online? To think about such questions is already to think about where you position your presentation of your own qualified self in relation to the practices that Lee Humphreys describes.

The diary - and as the first chapter of Humphreys's book shows, its long history - is actually a very interesting media form to be discussing at a time sometimes characterized as "post-digital," that has seen the publication of two books whose titles are revealing: David Sax's *The Revenge of Analog: Real Things and Why They Matter* (New York: PublicAffairs/Hachette Book Group, 2016); and Damon Krukowski's *The New Analog: Listening and Reconnecting in a Digital World* (New York: The New Press, 2017), along with its accompanying [podcast](https://www.radiotopia.fm/showcase/ways-of-hearing). The second chapter of Sax's book, titled "The Revenge of Paper," focuses on the resurgence, at the height of the digital age, of the [Moleskine notebook](https://www.moleskine.com/en-us/the-world-of-moleskine/) as the icon of the new analog age. While the current iteration of the brand prefers the term [planners](https://www.moleskine.com/en-us/shop/limited-editions/sakura/sakura-planner-20222023-bird-8056598851496.html) to diaries, its extensive product line of pocket-sized notebooks is of course modeled on precisely the miniature, portable format of historical diaries that Humphreys describes. I leave you to think about what Humphreys herself might say about this re-emergence of the 18C/19C diary format as a cultural phenomenon, but at the very least it seems to suggest a nostalgia, even at the height of the social media age, for the personal, individual format of the notebook and pen-and-paper writing. So this is, in part, why I'm curious about your own media practices - analog, digital, or both - in relation to personal journaling.

Humphreys's book can take us in a lot of interesting directions like this - another one might be towards the digital gardens movement that we've been looking at as part of the creative communities assignment. The quaintly pastoral concept of the digital garden itself evokes a similarly pre-digital form of cultural creativity, while the format of the digital garden itself seems like a modern-day descendant of the media formats that are arguably its historical ancestors. Digital gardens certainly share many characteristics of the diaries, scrapbooks, and photo-albums that Humphreys discusses, most nobably their shared, public dimension. Along with the Moleskine, then, we can also reflect on emerging social-media formats that are in many ways a continuation of historical social practices of documenting the everyday.

The central focus of Humphrey's book, of course, as well as its most significant conceptual move, is its shift of the discussion of the self in digital culture from the notion of the **quantified self** - which you're much more likely to have heard of - to the **qualified** self. This involves a corresponding shift from quantitative methodologies, which have tended to dominate the discussion of social media (metrics, analytics, etc.) to qualititative methodologies, which are more concerned with the symbolic dimension of social media technologies and their role in the formation of communities and social identities. This leads to my next question, about your own involvement in the self-tracking movement (associated with the concept of the quantified self). Essentially, if you use a FitBit or use your Apple watch for biometrics, you are! In which case, I'll be particularly interested to hear what you thought about Humphreys's discussion of what she calls the **datafication** of the self enabled by these portable devices, as well as her focus on the digital self a source not of data (whether for your own purposes or those of marketers) but of **mediating** our social relationships with our larger communitiy and ritually enacting our position within it.

Sidebar: the quantified self subculture has received bemused, if largely uncritical coverage in the mainstream press, but outside journalism not all of it has been positive: for a decidedly dystopian take, see the 2016 short film [The Quantified Self](https://vimeo.com/171114894).

This brings us to the conceptual distinction that is at the heart of Humphreys's approach, between the **transmission** and **ritual** models of communication. Since she doesn't explain this distinction directly, it may be useful to clarify what she's referring to. The specific reference is to the first chapter of the James Carey's book *Communication As Culture*, titled "A Cultural Approach to Communication," that has become something of a landmark since the book was first published (1989). This chapter is the source of the distinction to which Humphreys is referring.

Put simply, the dominant understanding of communication is in terms of what Carey calls the transmission model, a model originally derived from cybernetics and communication theory. This model conceives of communication as involving the transmission of a message via a simple model: sender \> channel \> receiver. So to take the example of a newspaper or a TV news broadcast, a transmission model of communication conceives this as essentially involving the transmission of information from a source an audience, with either the print format of the newspaper or the TV set as the channel. From this standpoint, the main areas of concern have to do with the transmission of the message itself, in terms of the quality of the signal and interference by noise (e.g. static).

Against this, Carey argues that communication needs to be understood not as a purely technical problem in terms of transmission, but as a cultural practice by which social identities and community ties are ritually constructed and reinforced. In this context, think of the etymological similarities between the term communication and words like community or communion (another term associated with ritual in Christianity). Carey's example of communication as a ritual practice that reinforces a sense of imagined community is to invite us to picture someone riding the subway on the morning commute, reading the national (or it could just be the city) newspaper and looking around at other people doing the same thing. The simultaneity with which people are performing the same daily ritual at the same time every morning reinforces the sense of what Benedict Anderson calls an "imagined community." It's still the same newspaper, but two very different ways of seeing it in relation to communication. Similar examples can be found in broadcast media, from evening news broadcasts to listening to National Public Radio on the morning/evening commute.

It's this ritual model of communication that Lee Humphreys is suggesting we apply to thinking about how communication works on social media platforms, and this explains her emphasis on social media practices and the ritual functions they serve in the reaffirmation both of social identity (through posting about everyday activities) and as speech acts reiterating our place within the wider community of which we are a part. From this standpoint, it makes more sense to study social media not just in quantitative terms, as a set of data points, but in qualitative ones, in terms of how the media traces of ourselves that we choose to share are, as Humphreys puts it (paraphrasing Carey), not just symbols *of* us, but *for* us, that actively construct and ritually perform the social identity that connects us to the community to which we belong (or would like to belong). This is what Humphreys refers to as the **identity work** that we perform in social media, both individually and more importantly, collectively.
