---
title: ""
format: html
editor: visual
---

> "Real people don't come with pause buttons." - Emily Weinstein and Carrie James, *Behind Their Screens*, p. 36.

## Got to BeReal: Staged Authenticity and the Myth of the Unmediated Self

I think all of us will have found this week's assigned chapters from Emily Weinstein and Carrie James's recent book *Behind Their Screens: What Teens Are Facing (And Adults Are Missing)* (Cambridge, MA: MIT Press, 2022) relatable on some level or another. The book represents the latest installment in what is by now a long line of books about teenagers and mobile devices, extending as far back as 2010 with Mizuko Ito et al's book *Hanging Out, Messing Around, and Geeking Out: Kids Living and Learning with New Media* (Cambridge, MA: MIT Press, 2010) and danah boyd's now classic study [*It's Complicated: The Social Lives of Networked Teens*](https://www.danah.org/) (New Haven: Yale University Press, 2014). While I could have assigned either of these books to look at teenage mobile use, since keeping current is so important in studying social media I thought it might be better to use Weinstein and James's new book as a reference point for the earlier works. For both of the assigned chapters, be sure also to read over the endnotes, which are a great source of references for possible future research on the subject. The section on the impact of screens on sleep is particularly interesting, and I'm uploading the report on the subject that's mentioned in the notes to the pdf folder on GitHub if anyone's interested in reading it.

While the chapters lay out many of the dilemmas faced by contemporary teenagers in a social media world, my main critique of them has to do with the analytical framework by which they seek to account for them, which as they explain is that of developmental psychology. This framework seems so natural and common-sense - since comparing oneself to others is a natural process of teenage development, it's **understandable** that teens should obsess so much about their Instagram feeds - that it seems somehow self-evident and beyond question: it **makes sense**, right? The problem with the framework lies in the fact that it bases its readings of teenage social behavior on a behaviorist framework derived from animal biology (ubiquitous pop-culture references to "alpha males" are an example of this behaviorist framework) that is universalist and ignores the fact that social behavior is not innate but **cultural**; and where there is culture there is difference. Do all "teens" around the world, regardless of their culture, share the same traits as the U.S. teens that Weinstein and James describe? Even if they do (which is questionable), can this not be attributed as much to cultural globalization as to supposedly universal stages of human development?

From this standpoint, the story near the beginning of the introduction to the book about James's observation of Saudi teenage behavior in a mall in Riyadh is very interesting. In spite of their superficial cultural difference from U.S. teenagers, the authors suggest, the teenagers are basically behaving the same as any other teenagers do, using their mobile devices to get around the cultural limitations placed upon them by a Muslim society. How seriously should we take this reassuringly universalist narrative? Were the Saudi teens even consulted about how they were using their phones (which would have required interviewing them in their own language), or were they simply observed from afar? The answer in this case seems to be the latter, and it seems to me that the episode seems to sum up how the book frames teen behavior not in terms of cultural specificity and difference, as a social anthropologist would, but in terms of what is claimed to be universal human behavior. This is obviously a complex question, but it's at least worth thinking about where cultural differnce comes into play in the developmentalist narrative about teenage use of social media.

While I'm curious to hear from everyone which sections of the readings you found particularly resonant, the one that I'd like to focus on here is the one called **Is Authenticity The New Perfect?** (44-45). As you'll recall, the section is about authenticity as one of the core values not just of social media but of contemporary culture more generally; or more specifically, the notion of authentic **identity**, and the desire both to access this in others and to project our own version of it. Many of you will be familiar with the trends referenced in the section, such as #nomakeup and other supposedly more authentic forms of self-representation. "Fakeness,"" or the perception of it, remains the kryptonite of any influencer today, the goal always being to appear as "authentic" as possible (even if, as Weinstein and James note, this doesn't necessarily make ordinary people feel any better...). In this context, I was wondering how many of you have tried out the new - or at least relatively recent - kid on the social media block: BeReal. If you've tried, you'll know how the app has been carefully positioned as a more "authentic" alternative to the ultra-stylized self-representation of Instagram. But you'll also know that the authentic self-representation that it calls for is in practice just another layer of inauthenticity, or simply so banal and everyday that it's of little interest to most people other than family and friends. This article from last week's UK paper *The Independent* lays out the problems with the app very well, so I'll just refer you to that:

Olivia Petter, "[BeReal promised online authenticity. Most of us have realised it's a scam](https://www.independent.co.uk/life-style/bereal-app-authenticity-instagram-b2226541.html?utm_source=pocket_saves#comments-area)," *The Independent*, 17 November 2022.

For all its faults, though, BeReal reveals a number of things. First, the paradoxical concept of **staged authenticity**, a term originally used in connection with the tourist industry: what may appear as authentic on closer examination turns out to be a staged version of it, and therefore by definition can't be truly authentic. Second, that real authenticity is actually not very interesting anyway, and may be at best meaningless, at worst disturbing to us as outsiders.

In the context of social media, why is at least the perception of authenticity so important? Because it holds at least the possibility of an unmediated encounter with someone like ourself, who is therefore "relatable." This raises the question of what a few years back Rebecca Mead called ["the scourge of relatability"](https://www.newyorker.com/culture/cultural-comment/scourge-relatability) - the tendency to evaluate everything from the standpoint of narcissistic identification (as Weinstein and James put it, "Mirror, Mirror, On The ... Screen"). I don't have space to go down that rabbit hole here, but would encourage you to read Mead's article.
